repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
        args: ['--allow-multiple-documents']
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: '1.11.2'
    hooks:
      - id: markdownlint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 'v1.25.0'
    hooks:
      - id: terraform_tflint
